# Generated by Django 2.1.3 on 2018-11-02 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_members', '0006_auto_20181102_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('U', 'Indéfini/Inconnu')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='responsable_bde_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.BdeSecurityGroup'),
        ),
        migrations.AlterField(
            model_name='team',
            name='responsable_insa_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.InsaSecurityGroup'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_bde_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.BdeSecurityGroup'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_insa_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.InsaSecurityGroup'),
        ),
    ]
