# Generated by Django 2.1.3 on 2019-04-06 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_members', '0007_auto_20181102_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='has_valid_membership',
            field=models.BooleanField(default=False, verbose_name='A la carte VA'),
        ),
        migrations.AlterField(
            model_name='team',
            name='responsable_bde_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.BdeSecurityGroup'),
        ),
        migrations.AlterField(
            model_name='team',
            name='responsable_insa_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.InsaSecurityGroup'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_bde_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.BdeSecurityGroup'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_insa_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.InsaSecurityGroup'),
        ),
    ]
