# Generated by Django 2.1.3 on 2019-04-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('active_members', '0008_auto_20190406_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subteam',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subTeams', to='active_members.LedMailing'),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resp', to='active_members.Member'),
        ),
        migrations.AlterField(
            model_name='team',
            name='resp_mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team', to='active_members.LedMailing'),
        ),
        migrations.AlterField(
            model_name='team',
            name='responsable_bde_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.BdeSecurityGroup'),
        ),
        migrations.AlterField(
            model_name='team',
            name='responsable_insa_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.InsaSecurityGroup'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_bde_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.BdeSecurityGroup'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_insa_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='active_members.InsaSecurityGroup'),
        ),
    ]
